config/routes.rb
Rails.application.routes.draw do
  resources :galeries
  resources :contacts, only: [:new, :create]
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  root 'pages#home'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => true
  attribute :file,      :attachment => true
  attribute :number,    :validate => true
  attribute :message
  attribute :nickname,  :captcha  => true

  validates :name, length: { minimum: 10, message: "Debe por lo menos tener más 10 caracteres" }
  validates :number, numericality: { only_integer: true }, presence: { message: "Debe colocar solamente cifras" }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "El correo es invalido"

	  def headers 
	  	{
	  	:subject => "Contact Form",
	  	:to => "saffronpuntacana@gmail.com",
	  	:from => %("#{name}" <#{email}>)
	  }
	end
end

app/models/galery.rb
class Galery < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message'
			render :new
		end
	end
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
  before_action :set_galery, only: [:show, :edit, :update, :destroy]

  # GET /galeries
  # GET /galeries.json
  def index
    @galeries = Galery.all
  end

  # GET /galeries/1
  # GET /galeries/1.json
  def show
  end

  # GET /galeries/new
  def new
    @galery = Galery.new
  end

  # GET /galeries/1/edit
  def edit
  end

  # POST /galeries
  # POST /galeries.json
  def create
    @galery = Galery.new(galery_params)

    respond_to do |format|
      if @galery.save
        format.html { redirect_to @galery, notice: 'Galery was successfully created.' }
        format.json { render :show, status: :created, location: @galery }
      else
        format.html { render :new }
        format.json { render json: @galery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeries/1
  # PATCH/PUT /galeries/1.json
  def update
    respond_to do |format|
      if @galery.update(galery_params)
        format.html { redirect_to @galery, notice: 'Galery was successfully updated.' }
        format.json { render :show, status: :ok, location: @galery }
      else
        format.html { render :edit }
        format.json { render json: @galery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeries/1
  # DELETE /galeries/1.json
  def destroy
    @galery.destroy
    respond_to do |format|
      format.html { redirect_to galeries_url, notice: 'Galery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galery
      @galery = Galery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galery_params
      params.require(:galery).permit(:name, :description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div class="container">
	<h1>Gracias por tu mensaje!</h1>
	<p>Te contestaremos lo antes posible!</p>
</div>

app/views/contacts/new.html.erb
<div class="container">
	<h1 class="page_title"> Contáctanos!</h1>
		<%= form_for @contact do |f| %>
			<% if @contact.errors.full_messages.any? %>
  				<% @contact.errors.full_messages.each do |error_message| %>
  				<div class="alert alert-danger" role="alert">
  					<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  					<span class="sr-only">Error:</span>
  					<%= error_message  %> 
				</div>
 				 <% end %>				
			<% end %>
			<%= f.label :Nombre  %><br>
			<%= f.text_field :name, class: "form-control", required: true %>

			<br>

			<%= f.label :Correo %><br>
			<%= f.text_field :email, class: "form-control", required: true %>

			<br>

			<%= f.label :Mobil %><br>
			<%= f.text_field :number, class: "form-control", required: true %>

			<br>

			<%= f.label :Mensaje %><br>
			<%= f.text_area :message, class: "form-control", as: :text %>

			<br>

			<div class="hidden">
				<%= f.label :nickname %><br>
				<%= f.text_field :nickname, class: "form-control",  hint: 'Leave this filed blank' %>
			</div>

			<%= f.submit 'Enviar Mensaje', class: "btn btn-primary"%>

		<% end %>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.348632626699!2d-68.3858584859911!3d18.55831467286448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8ea893d541c83c23%3A0xf9b13f8097de0e8f!2sBlueMall+Puntacana!5e0!3m2!1sen!2sdo!4v1515537029569" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe><br>
	    	<strong>Dirección:</strong><p class="dir">Boulevard turístico, esquina Carretera Juanillo, Blue Mall, Punta Cana, República Dominicana.</p>
	    	<p><strong>Teléf:</strong> (809) 784-4141</br>
	    	<strong>E-mail:</strong> saffronpuntacana@gmail.com</p> 
</div>

app/views/galeries/_form.html.erb
<%= form_for @galery, :html => { :multipart => true } do |f| %>
  <% if @galery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galery.errors.count, "error") %> prohibited this galery from being saved:</h2>

      <ul>
      <% @galery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/galeries/edit.html.erb
<h1>Editing Galery</h1>

<%= render 'form' %>


	<%= link_to 'Show', @galery, class: "btn btn-link" %> |
	<%= link_to 'Back', galeries_path, class: "btn btn-link" %>

app/views/galeries/index.html.erb
<h3>Galería</h3>
<div class="center">
<div class="row">
<% @galeries.each do |galery| %>
  <div class="col-md-3">
    <div class="thumbnail">
    <%= image_tag galery.image.url %>
      <div class="caption">
        <h3><%= galery.name %></h3>
        <p><%= galery.description %></p>
        <%= link_to 'Show', galery, class: "btn btn-link" %>
            <%= link_to 'Edit', edit_galery_path(galery), class: "btn btn-link" %>
            <%= link_to 'Destroy', galery, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
      </div>
    </div>
  </div>  
  <% end %>
</div>
</div>



  <%= link_to 'New Galery', new_galery_path, class: "btn btn-link" %>

app/views/galeries/new.html.erb
	<h1>New Galery</h1>

	<%= render 'form' %>

	<%= link_to 'Back', galeries_path, class: "btn btn-link" %>

app/views/galeries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @galery.image_url.to_s %>
		</div>
	</div>
	<div class="col-md-6">
		<h3><%= @galery.name %></h3>
		<p><%= @galery.description %></p>
	</div>
</div>


<%= link_to 'Edit', edit_galery_path(@galery), class: "btn btn-link" %> |
<%= link_to 'Back', galeries_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">
<div class="container">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	 <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        </div>
        <div class="col-md-4">
          <h2 class="">Contact</h2>
          <ul>
          	<li><b>Dirección:</b> Boulevard turístico, esquina Carretera Juanillo, Blue Mall, Punta Cana, República Dominicana.</li>
          	<li><b>Correo:</b> <a href="mailto:saffronpuntacana@gmail.com">saffronpuntacana@gmail.com</a></li>
          	<li><b>Teléfono:</b> (809) 784-4141</li>
          </ul>
        </div>
    </div>
	<a href="https://www.facebook.com/profile.php?id=100017992084074" class="fa fa-facebook" style="font-size: 30px; width: 80px; padding: 25px;"></a>
	<a href="https://twitter.com/Saffron_RD?lang=en" class="fa fa-twitter" style="font-size: 30px; width: 80px; padding: 25px;"></a>
	<a href="https://www.instagram.com/saffronpuntacana/?hl=en" class="fa fa-instagram" style="font-size: 30px; width: 80px; padding: 25px;"></a>

	<p style="margin-right:290px; float:right;"><strong>Developed by:</strong></p>
    <div class="eso" style="border-radius: 500px;background: #bb85c8; none repeat scroll 0% 0%;width: 90px; height: 90px; float: right; font-size: 33px; margin-right:220px; margin-top: -75px;"><p style="margin-left: 11px; padding-top: 23px;width: 10px; height: 10px;color: #000000;">ESO</p>  
</div>
</div>
<div>

<div class="footer">
    <p class="final">Copyright© 2017 Saffron. All rights reserved</p>
</div>

app/views/layouts/_header.html.erb
<div class="header-img">
  <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation"><a class ="active" href="/">Inicio</a></li>
            <li role="presentation"><a class ="active" href="/pages/about">Sobre</a></li>
            <li role="presentation"><a class ="active" href="/galeries">Galería</a></li>
            <li role="presentation"><a class ="active" href="/contacts/new">Contacto</a></li>
          </ul>
        </nav>
        <a href="/">
          <%= cl_image_tag("logo_saffron_white_bejlq8.png", :width => 300, :height => 135)%>
        </a>
      </div>
  </div>
</div>    

<%# 
<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation"><a class ="active" href="/">Home</a></li>
            <li role="presentation"><a class ="active" href="/pages/about">About</a></li>
            <li role="presentation"><a class ="active" href="/pages/contact">Contact</a></li>
          </ul>
        </nav>
        <a href="/">
          <img alt="Icon" src="/assets/logo_saffron.png"/>
        </a>
      </div>
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saffronrd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'logo_saffron.ico' %>
</head>
<%= render'layouts/header' %>
<body>

<%= yield %>

</body>
<%= render'layouts/footer' %>
</html>

app/views/pages/about.html.erb
	<hr class="featurette-divider">
	<div class="row featurette">
		<div class="col-md-7">
	    	<h2 class="featurette-heading">Historia</h2>
			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
		</div>
	<div class="col-md-5">
		<img class="featurette-image img-responsive center-block" src="/assets/wine.jpg" alt="Generic placeholder image" style="width: 250px; height: 250px; margin-top: -10px;">
	</div>
	</div>

<div class="black_background">
      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Hoy en día</h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" src="/assets/meat.jpg" alt="Dining" style="width: 250px; height: 250px; margin-top: -10px;">
        </div>
      </div>
</div>


<hr class="featurette-divider">
	<div class="row featurette">
		<div class="col-md-7">
	    	<h2 class="featurette-heading">Metas</h2>
			<p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
		</div>
	<div class="col-md-5">
		<img class="featurette-image img-responsive center-block" src="/assets/tacobellini.jpg" alt="Generic placeholder image" style="width: 250px; height: 250px; margin-top: -10px;">
	</div>
	</div>
</div>
<div class="container">
    <div class="row">
    	<div class="col_1">
                	<div class="circle_1">
                			<span class="glyphicon glyphicon-user" style="padding-left: 55px;font-size: 52px;padding-top: 50px;" aria-hidden="true"></span>
        					<span class="sr-only">Previous</span>
                	</div>
                	<h2>Our testimonial</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique tristique lacus in varius. Donec nec vestibulum ligula. Aenean turpis diam, feugiat a luctus in, rhoncus eget risus. Maecenas consequat porttitor dui, vitae consequat massa imperdiet ut. elit ut tempus lobortis, eros leo molestie velit.</p>
                </div>
                <div class="col_2">
                <div class="circle_1">
                			<span class="glyphicon glyphicon-book" style="padding-left: 55px;font-size: 52px;padding-top: 50px;" aria-hidden="true"></span>
        					<span class="sr-only">Previous</span>
                	</div>
                	<h2>Our testimonial</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique tristique lacus in varius. Donec nec vestibulum ligula. Aenean turpis diam, feugiat a luctus in, rhoncus eget risus. Maecenas consequat porttitor dui, vitae consequat massa imperdiet ut. elit ut tempus lobortis, eros leo molestie velit.</p>
                </div>
                <div class="col_3">
                <div class="circle_1"> 
                			<span class="glyphicon glyphicon-road" style="padding-left: 55px;font-size: 52px;padding-top: 50px;" aria-hidden="true"></span>
        					<span class="sr-only">Previous</span>
                	</div>
                	<h2>Our testimonial</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique tristique lacus in varius. Donec nec vestibulum ligula. Aenean turpis diam, feugiat a luctus in, rhoncus eget risus. Maecenas consequat porttitor dui, vitae consequat massa imperdiet ut. elit ut tempus lobortis, eros leo molestie velit.</p>
                </div>  
                </div>
    </div>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<form action="submit.php" method="post">
	        <fieldset>
	        	<div class="form-group">
	            	<label>Nombre:</label><br>
	                <input type="text" name="name" placeholder="Nombre Completo" class="form-control">
	             </div>
	             <div class="form-group">
	            	<label>E-mail:</label><br>
	                <input type="text" name="email" placeholder="Correo Electrónico" class="form-control">
	             </div>
	             <div class="form-group">
	            	<label>Número de teléfono:</label><br>
	                <input type="text" name="number" placeholder="Número de contacto" class="form-control">
	             </div>
	             <div class="form-group">
	            	<label>Comentario:</label><br>
	                <textarea name="comment" role="20" cols="50" placeholder="Escriba su comentario" class="form-control"></textarea>
	             </div>
	             <div class="form-group">
	            	 <input class="btn btn-primary" type="submit" value="Enviar"><br></label></form> 
	             </div>
	        </fieldset>     
	    </form>
	    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.348632626699!2d-68.3858584859911!3d18.55831467286448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8ea893d541c83c23%3A0xf9b13f8097de0e8f!2sBlueMall+Puntacana!5e0!3m2!1sen!2sdo!4v1515537029569" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
	    	<strong>Dirección:</strong><p class="dir">Calle Salomé Ureña #59, Zona Colonial, Santo Domingo, República Dominicana.</p>
	    	<p><strong>Teléf:</strong> (809)-687-2526</br>
	    	<strong>E-mail:</strong> fundacion.americard@gmail.com</p>  
</div>           

app/views/pages/home.html.erb
<div class="container">
	<div class="row">
	        <div class="col-lg-4">
	          <%= cl_image_tag("cr_ipnvhv.jpg", :class => "img-circle", :width => 140, :height => 140) %>
	        </div>
	</div>
	<h2 class="bluemall">Bluemall Puntacana</h2>
	<p class="pbluemall">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
</div>

<div class="black_background">
	<div class="container">
			<hr class="featurette-divider">
				<div class="row featurette">
			        <div class="col-md-7">
			          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
			          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
			        </div>
			        <div class="col-md-5">
			        	 <%= cl_image_tag("wine_ckcmne.jpg", :class => "featurette-image img-responsive center-block", :width => 500, :height => 500, :alt => "Generic placeholder image") %>
			        </div>
	    </div>
	</div>
</div>

<div class="container">
 <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
        	<%= cl_image_tag("meat_gvabpv.jpg", :class => "featurette-image img-responsive center-block", :width => 500, :height => 500, :alt => "Generic placeholder image") %>
        </div>
      </div>
</div>


<div class="black_background">
	<div class="container">
			<hr class="featurette-divider">
				<div class="row featurette">
			        <div class="col-md-7">
			          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
			          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
			        </div>
			        <div class="col-md-5">
			          <%= cl_image_tag("tacobellini_d6igyu.jpg", :class => "featurette-image img-responsive center-block", :width => 500, :height => 500, :alt => "Generic placeholder image") %>
			        </div>
	    </div>
	</div>
</div>